webtalk_init -webtalk_dir /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.sim/sim_1/synth/func/xsim.dir/gslcd_v1_0_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 22 23:02:10 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1909853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c6022c5398005ffba4c737b266737e54" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9ca38e96aafc4caaac3f4f822a332995" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 9.0 (stretch)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2903.079 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "15" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "777 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "138 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "4134" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "884" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "292408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 494245967 -regid "" -xml /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.sim/sim_1/synth/func/xsim.dir/gslcd_v1_0_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.sim/sim_1/synth/func/xsim.dir/gslcd_v1_0_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.sim/sim_1/synth/func/xsim.dir/gslcd_v1_0_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
