# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gameslab/gameslab.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab || ORIG_REF_NAME==gameslab}]

# IP: bd/gameslab/ip/gameslab_processing_system7_0_0/gameslab_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_processing_system7_0_0 || ORIG_REF_NAME==gameslab_processing_system7_0_0}]

# XDC: bd/gameslab/gameslab_ooc.xdc
