# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gameslab.xdc

# Block Designs: bd/gameslab/gameslab.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab || ORIG_REF_NAME==gameslab}]

# IP: bd/gameslab/ip/gameslab_processing_system7_0_0/gameslab_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_processing_system7_0_0 || ORIG_REF_NAME==gameslab_processing_system7_0_0}]

# IP: bd/gameslab/ip/gameslab_gslcd_0_2/gameslab_gslcd_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_gslcd_0_2 || ORIG_REF_NAME==gameslab_gslcd_0_2}]

# IP: bd/gameslab/ip/gameslab_xlconstant_0_0/gameslab_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_xlconstant_0_0 || ORIG_REF_NAME==gameslab_xlconstant_0_0}]

# IP: bd/gameslab/ip/gameslab_ps7_0_axi_periph_0/gameslab_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_ps7_0_axi_periph_0 || ORIG_REF_NAME==gameslab_ps7_0_axi_periph_0}]

# IP: bd/gameslab/ip/gameslab_rst_ps7_0_100M_0/gameslab_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_rst_ps7_0_100M_0 || ORIG_REF_NAME==gameslab_rst_ps7_0_100M_0}]

# IP: bd/gameslab/ip/gameslab_auto_pc_0/gameslab_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gameslab_auto_pc_0 || ORIG_REF_NAME==gameslab_auto_pc_0}]

# XDC: bd/gameslab/gameslab_ooc.xdc
