# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/craigjb/Projects/gameslab-hw/gameslab-hw.cache/wt [current_project]
set_property parent.project_path /home/craigjb/Projects/gameslab-hw/gameslab-hw.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part craigjb.com:gameslab:part0:1.0 [current_project]
set_property ip_repo_paths {
  /home/craigjb/Projects/ip_repo/test_1.0
  /home/craigjb/Projects/ip_repo/gslcd_1.0
} [current_project]
set_property ip_output_repo /home/craigjb/Projects/gameslab-hw/gameslab-hw.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/hdl/gameslab_wrapper.v
add_files /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/gameslab.bd
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_processing_system7_0_0/gameslab_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_rst_ps7_0_100M_0/gameslab_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_rst_ps7_0_100M_0/gameslab_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_rst_ps7_0_100M_0/gameslab_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_ila_0_0/gameslab_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_auto_pc_1/gameslab_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/ip/gameslab_auto_pc_0/gameslab_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/gameslab_ooc.xdc]
set_property is_locked true [get_files /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/sources_1/bd/gameslab/gameslab.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/constrs_1/new/gameslab.xdc
set_property used_in_implementation false [get_files /home/craigjb/Projects/gameslab-hw/gameslab-hw.srcs/constrs_1/new/gameslab.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top gameslab_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef gameslab_wrapper.dcp

catch { report_utilization -file gameslab_wrapper_utilization_synth.rpt -pb gameslab_wrapper_utilization_synth.pb }
