# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part craigjb.com:gameslab:part0:1.0 [current_project]
set_property ip_repo_paths /home/craigjb/Projects/ip_repo/gslcd_1.0 [current_project]
set_property ip_output_repo /home/craigjb/Projects/gameslab-hw/gameslab-hw.tmp/gslcd_v1_0_project/gslcd_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/craigjb/Projects/ip_repo/gslcd_1.0/hdl/gslcd_v1_0_M00_AXI.v
  /home/craigjb/Projects/ip_repo/gslcd_1.0/hdl/gslcd_v1_0_S00_AXI.v
  /home/craigjb/Projects/ip_repo/gslcd_1.0/hdl/gslcd_v1_0_fifo_32to24.v
  /home/craigjb/Projects/ip_repo/gslcd_1.0/hdl/gslcd_v1_0_timing.v
  /home/craigjb/Projects/ip_repo/gslcd_1.0/hdl/gslcd_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top gslcd_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef gslcd_v1_0.dcp

catch { report_utilization -file gslcd_v1_0_utilization_synth.rpt -pb gslcd_v1_0_utilization_synth.pb }
